--- 
stages: 
  - name: Build Stage
    inputs: 
      - type: git
        branch: master
    triggers: 
      - type: commit
    jobs: 
      - name: Build
        type: builder
  - name: Deploy Stage
    inputs: 
      - type: job
        stage: Build Stage
        job: Build
    triggers: 
      - type: stage
    jobs: 
      - name: Deploy to dev
        type: deployer
        script: |-
            #!/bin/bash
            cf push "${CF_APP}" --no-start
            cf create-service iotf-service iotf-service-free iotp-service-for-phone
            cf bind-service "${CF_APP}" iotp-service-for-phone
            cf start "${CF_APP}"
            # View logs
            cf logs "${CF_APP}" --recent
        target: 
          organization: ${CF_ORGANIZATION}
          space: ${CF_SPACE}
          url: ${CF_TARGET_URL}
          application: ${CF_APP}

